# Data Collection

In [21]:
import pandas as pd
import numpy as np

---

### Results

In [22]:
results = pd.read_csv('./data/results.csv')
results.head()
# data from kaggle:  https://www.kaggle.com/martj42/international-football-results-from-1872-to-2017?select=results.csv

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [23]:
results.shape

(43045, 9)

In [24]:
results[results['date'] < '1992-12-31'].shape  # <- 1st date of FIFA rankings

(17489, 9)

In [25]:
results.drop(results[results['date'] < '1992-12-31'].index, inplace=True)

In [26]:
results.shape

(25556, 9)

In [27]:
results.reset_index(inplace=True)

In [28]:
results.drop(columns='index', inplace=True)
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1993-01-01,Ghana,Mali,1.0,1.0,Friendly,Libreville,Gabon,True
1,1993-01-02,Gabon,Burkina Faso,1.0,1.0,Friendly,Libreville,Gabon,False
2,1993-01-02,Kuwait,Lebanon,2.0,0.0,Friendly,Kuwait City,Kuwait,False
3,1993-01-03,Burkina Faso,Mali,1.0,0.0,Friendly,Libreville,Gabon,True
4,1993-01-03,Gabon,Ghana,2.0,3.0,Friendly,Libreville,Gabon,False

---

### CONCACAF World Cup Qualifying Fixtures

In [29]:
qualifying_fixtures = pd.read_csv('./data/concacaf_wcq_fixtures.csv')

# data from FIFA site:  https://www.fifa.com/tournaments/mens/worldcup/qatar2022/qualifiers/concacaf

In [30]:
qualifying_fixtures[qualifying_fixtures['date'].isnull()]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
qualifying_fixtures.drop(index=qualifying_fixtures[qualifying_fixtures['date'].isnull()].index, inplace=True)

In [32]:
qualifying_fixtures

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,2021-09-02,Canada,Honduras,1.0,1.0,FIFA World Cup qualification,Toronto,Canada,False
1,2021-09-02,Panama,Costa Rica,0.0,0.0,FIFA World Cup qualification,Panama City,Panama,False
2,2021-09-02,Mexico,Jamaica,2.0,1.0,FIFA World Cup qualification,Mexico City,Mexico,False
3,2021-09-02,El Salvador,United States,0.0,0.0,FIFA World Cup qualification,San Salvador,El Salvador,False
4,2021-09-05,Jamaica,Panama,0.0,3.0,FIFA World Cup qualification,Kingston,Jamaica,False
5,2021-09-05,El Salvador,Honduras,0.0,0.0,FIFA World Cup qualification,San Salvador,El Salvador,False
6,2021-09-05,Costa Rica,Mexico,0.0,1.0,FIFA World Cup qualification,San Jose,Costa Rica,False
7,2021-09-05,United States,Canada,1.0,1.0,FIFA World Cup qualification,Nashville,United States,False
8,2021-09-08,Canada,El Salvador,3.0,0.0,FIFA World Cup qualification,Toronto,Canada,False
9,2021-09-08,Panama,Mexico,1.0,1.0,FIFA World Cup qualification,Panama City,Panama,False
10,2021-09-08,Costa Rica,Jamaica,1.0,1.0,FIFA World Cup qualification,San Jose,Costa Rica,False
11,2021-09-08,Honduras,United States,1.0,4.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False
12,2021-10-07,Honduras,Costa Rica,0.0,0.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False
13,2021-10-07,United States,Jamaica,2.0,0.0,FIFA World Cup qualification,Austin,United States,False
14,2021-10-07,Mexico,Canada,1.0,1.0,FIFA World Cup qualification,Mexico City,Mexico,False
15,2021-10-07,El Salvador,Panama,1.0,0.0,FIFA World Cup qualification,San Salvador,El Salvador,False
16,2021-10-10,Jamaica,Canada,0.0,0.0,FIFA World Cup qualification,Kingston,Jamaica,False
17,2021-10-10,Panama,United States,1.0,0.0,FIFA World Cup qualification,Panama City,Panama,False
18,2021-10-10,Costa Rica,El Salvador,2.0,1.0,FIFA World Cup qualification,San Jose,Costa Rica,False
19,2021-10-10,Mexico,Honduras,3.0,0.0,FIFA World Cup qualification,Mexico City,Mexico,False
20,2021-10-12,United States,Costa Rica,2.0,1.0,FIFA World Cup qualification,Columbus,United States,False
21,2021-10-13,Canada,Panama,4.0,1.0,FIFA World Cup qualification,Toronto,Canada,False
22,2021-10-13,Honduras,Jamaica,0.0,2.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False
23,2021-10-13,El Salvador,Mexico,0.0,2.0,FIFA World Cup qualification,San Salvador,El Salvador,False
24,2021-11-11,United States,Mexico,2.0,0.0,FIFA World Cup qualification,Cincinnati,United States,False
25,2021-11-12,Honduras,Panama,2.0,3.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False
26,2021-11-12,El Salvador,Jamaica,1.0,1.0,FIFA World Cup qualification,San Salvador,El Salvador,False
27,2021-11-12,Canada,Costa Rica,1.0,0.0,FIFA World Cup qualification,Edmonton,Canada,False
28,2021-11-16,Jamaica,United States,1.0,1.0,FIFA World Cup qualification,Kingston,Jamaica,False
29,2021-11-16,Panama,El Salvador,2.0,1.0,FIFA World Cup qualification,Panama City,Panama,False
30,2021-11-16,Costa Rica,Honduras,2.0,1.0,FIFA World Cup qualification,San Jose,Costa Rica,False
31,2021-11-16,Canada,Mexico,2.0,1.0,FIFA World Cup qualification,Edmonton,Canada,False
32,2022-01-26,Jamaica,Mexico,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
33,2022-01-26,Honduras,Canada,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
34,2022-01-26,United States,El Salvador,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
35,2022-01-26,Costa Rica,Panama,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
36,2022-01-29,Honduras,El Salvador,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
37,2022-01-29,Panama,Jamaica,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
38,2022-01-29,Canada,United States,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
39,2022-01-29,Mexico,Costa Rica,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
40,2022-02-01,Jamaica,Costa Rica,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
41,2022-02-01,United States,Honduras,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
42,2022-02-01,Mexico,Panama,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
43,2022-02-01,El Salvador,Canada,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
44,2022-03-23,Jamaica,El Salvador,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
45,2022-03-23,Panama,Honduras,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
46,2022-03-23,Mexico,United States,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
47,2022-03-23,Costa Rica,Canada,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
48,2022-03-26,United States,Panama,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
49,2022-03-26,Honduras,Mexico,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
50,2022-03-26,El Salvador,Costa Rica,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
51,2022-03-26,Canada,Jamaica,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
52,2022-03-29,Mexico,El Salvador,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
53,2022-03-29,Jamaica,Honduras,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
54,2022-03-29,Panama,Canada,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN
55,2022-03-29,Costa Rica,United States,NaN,NaN,FIFA World Cup qualification,NaN,NaN,NaN

---

### Current Table DF

In [33]:
table = pd.read_csv('./data/current_table_12.14.2021.csv')
table
# data from FIFA site:  https://www.fifa.com/tournaments/mens/worldcup/qatar2022/qualifiers/concacaf

,rank,team_name,matches_played,wins,draws,losses,goals_for,goals_against,goal_differential,points
0,1,Canada,8,4,4,0,13,5,8,16
1,2,USA,8,4,3,1,12,5,7,15
2,3,Mexico,8,4,2,2,11,7,4,14
3,4,Panama,8,4,2,2,11,9,2,14
4,5,Costa Rica,8,2,3,3,6,7,-1,9
5,6,Jamaica,8,1,4,3,6,10,-4,7
6,7,El Salvador,8,1,3,4,4,10,-6,6
7,8,Honduras,8,0,3,5,5,15,-10,3

---

### World Rankings

In [34]:
past_rankings = pd.read_csv('./data/fifa_ranking_up_to_2021-05-27.csv')
past_rankings.head()
# data from kaggle:  https://www.kaggle.com/cashncarry/fifaworldranking

,id,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,43818,82,Iraq,IRQ,15,0,0,AFC,12/31/1992
1,43873,107,Mozambique,MOZ,9,0,0,CAF,12/31/1992
2,43816,108,Indonesia,IDN,9,0,0,AFC,12/31/1992
3,1882218,109,Antigua and Barbuda,ATG,8,0,0,CONCACAF,12/31/1992
4,43820,110,Jordan,JOR,8,0,0,AFC,12/31/1992

In [35]:
past_rankings = past_rankings[['rank', 'country_full', 'rank_date']]
past_rankings.tail()

       rank         country_full  rank_date
63050   137             Tanzania  5/27/2021
63051   136             Suriname  5/27/2021
63052   135  St. Kitts and Nevis  5/27/2021
63053   159            Singapore  5/27/2021
63054     2               France  5/27/2021

In [36]:
past_rankings.shape

(63055, 3)

In [37]:
recent_rankings = pd.read_csv('./data/fifa_ranking_2021-08-12_to_2021-11-19.csv')
recent_rankings.head()
# data from FIFA:  https://www.fifa.com/fifa-world-ranking/

   rank country_full   rank_date
0   1.0      Belgium  2021-08-12
1   2.0       Brazil  2021-08-12
2   3.0       France  2021-08-12
3   4.0      England  2021-08-12
4   5.0        Italy  2021-08-12

In [38]:
rankings = pd.concat([past_rankings, recent_rankings])
rankings.shape

(64733, 3)

In [39]:
rankings.reset_index(inplace=True)
rankings.drop(columns='index', inplace=True)
rankings.dropna(inplace=True)
rankings

        rank            country_full   rank_date
0       82.0                    Iraq  12/31/1992
1      107.0              Mozambique  12/31/1992
2      108.0               Indonesia  12/31/1992
3      109.0     Antigua and Barbuda  12/31/1992
4      110.0                  Jordan  12/31/1992
...      ...                     ...         ...
63890  206.0                    Guam  2021-11-19
63891  207.0       US Virgin Islands  2021-11-19
63892  208.0  British Virgin Islands  2021-11-19
63893  209.0                Anguilla  2021-11-19
63894  210.0              San Marino  2021-11-19

[63895 rows x 3 columns]

---

# Combining and Cleaning the Data

In [40]:
# Creating columns that will be used as features for models
results['home_rank'] = 0
results['away_rank'] = 0
results['h_goals_for_avg'] = 0
results['h_goals_against_avg'] = 0
results['a_goals_for_avg'] = 0
results['a_goals_against_avg'] = 0

results['datetime'] = pd.to_datetime(results['date'])
rankings['datetime'] = pd.to_datetime(rankings['rank_date'])


# These results and rankings contain matches we are looking to predict so we will drop them from the dataset we will
# use to train our models on.
results.drop(results[(results['datetime'] > '2021-09-01 00:00:00')].index, inplace=True)
rankings.drop(rankings[(rankings['datetime'] > '2021-09-01 00:00:00')].index, inplace=True)

In [88]:
# Dropping games for teams that are not FIFA members and do not have a FIFA ranking
# Need to run twice

non_fifa_teams = ['Martinique', 'French Guiana', 'Guadeloupe', 'Guernsey', 'Ynys Môn', 'Isle of Wight', 'Åland Islands',
                  'Jersey', 'Isle of Man', 'Greenland', 'Shetland', 'Basque Country', 'Sint Maarten', 'Zanzibar', 
                  'Canary Islands', 'Frøya', 'Hitra', 'Catalonia', 'Corsica', 'Brittany', 'Palau', 'Gotland', 
                  'Saare County', 'Rhodes', 'Micronesia', 'Andalusia', 'Kernow', 'Saint Martin', 'Orkney', 'Monaco', 
                  'Tuvalu', 'Sark', 'Alderney', 'Kiribati', 'Mayotte', 'Western Isles', 'Falkland Islands', 'Réunion', 
                  'Galicia', 'Northern Cyprus', 'Republic of St. Pauli', 'Găgăuzia', 'Tibet', 'Occitania', 'Sápmi', 
                  'Silesia', 'Northern Mariana Islands', 'Menorca', 'Provence', 'Arameans Suryoye', 'Padania', 
                  'Iraqi Kurdistan', 'Gozo', 'Bonaire', 'Western Sahara', 'Raetia', 'Darfur', 'Tamil Eelam', 'Abkhazia', 
                  'Saint Pierre and Miquelon', 'Artsakh', 'Madrid', 'Vatican City', 'Ellan Vannin', 'South Ossetia', 
                  'County of Nice', 'Székely Land', 'Romani people', 'Felvidék', 'Chagos Islands', 
                  'United Koreans in Japan', 'Somaliland', 'Western Armenia', 'Barawa', 'Kárpátalja', 'Yorkshire', 
                  'Panjab', 'Cascadia', 'Matabeleland', 'Kabylia', 'Parishes of Jersey', 'Saint Helena', 'Chameria', 
                  'Wallis Islands and Futuna', 'Crimea']

for team in non_fifa_teams:
    results.drop(results[results['home_team'].str.contains(team)].index, inplace=True)
    results.drop(results[results['away_team'].str.contains(team)].index, inplace=True)

In [89]:
# Dropping matches for countries prior to their first FIFA ranking
# Need to run twice

teams = ['United Arab Emirates', 'Netherlands', 'Guyana', 'Cayman Islands', 'Thailand', 'Sri Lanka','Vietnam', 
         'Latvia', 'Macau', 'Bahrain', 'Algeria', 'Dominican Republic', 'Fiji', 'Slovakia', 'Anguilla', 'Dominica', 
         'Czech Republic', 'Azerbaijan', 'Turkmenistan', 'Gibraltar', 'Georgia', 'North Macedonia', 'Kazakhstan', 
         'Uzbekistan', 'Tajikistan', 'Papua New Guinea', 'Samoa', 'Tonga', 'Montserrat', 'Montenegro', 
         'Serbia and Montenegro', 'Curaçao', 'Cook Islands', 'Guam', 'New Caledonia', 'Bosnia and Herzegovina', 
         'Andorra', 'British Virgin Islands', 'Palestine', 'US Virgin Islands', 'São Tomé and Príncipe', 'Bhutan', 
         'Afghanistan', 'Kosovo', 'South Sudan', 'Moldova', 'Armenia', 'American Samoa', 'Djibouti', 'Eritrea', 
         'Belize', 'Turks and Caicos Islands', 'Comoros', 'St. Kitts and Nevis', 'East Timor', 'DR Congo']

rank_dates = ['1993-08-08 00:00:00', '1993-08-08 00:00:00', '1993-08-08 00:00:00', '1993-08-08 00:00:00', 
              '1993-08-08 00:00:00', '1993-08-08 00:00:00', '1993-08-08 00:00:00', '1993-08-08 00:00:00', 
              '1993-08-08 00:00:00', '1993-08-08 00:00:00','1993-08-08 00:00:00', '1993-08-08 00:00:00', 
              '1993-08-08 00:00:00', '1993-11-19 00:00:00', '1997-05-14 00:00:00', '1995-02-20 00:00:00', 
              '1994-03-15 00:00:00', '1994-06-14 00:00:00', '1994-10-25 00:00:00', '2016-09-15 00:00:00', 
              '1994-03-15 00:00:00', '1994-05-17 00:00:00', '1994-11-22 00:00:00', '1994-10-25 00:00:00', 
              '1994-11-22 00:00:00', '1996-09-25 00:00:00', '1996-11-20 00:00:00', '1996-11-20 00:00:00', 
              '1999-03-24 00:00:00', '2007-06-13 00:00:00', '2002-12-18 00:00:00', '2007-06-13 00:00:00', 
              '1996-11-20 00:00:00', '1996-08-28 00:00:00', '2004-06-09 00:00:00', '1996-05-22 00:00:00', 
              '1996-11-20 00:00:00', '1997-05-14 00:00:00', '1998-12-23 00:00:00', '1999-03-24 00:00:00', 
              '1998-08-19 00:00:00', '2000-08-09 00:00:00', '2003-01-15 00:00:00', '2016-07-14 00:00:00', 
              '2012-08-08 00:00:00', '1994-05-17 00:00:00', '1994-06-14 00:00:00', '1998-10-21 00:00:00', 
              '1994-12-20 00:00:00', '1998-10-21 00:00:00', '1995-12-19 00:00:00', '1999-03-24 00:00:00', 
              '2006-12-18 00:00:00', '1993-12-23 00:00:00', '2006-11-22 00:00:00', '1999-12-22 00:00:00']

team_and_rankdate = list(zip(teams, rank_dates))

for team in team_and_rankdate:
    results.drop(results[(results['home_team'] == team[0]) & (results['datetime'] < team[1])].index, inplace=True)
    results.drop(results[(results['away_team'] == team[0]) & (results['datetime'] < team[1])].index, inplace=True)

In [90]:
# Ensuring country name matches in rankings and results dataframes
# Need to run twice

rankings.loc[rankings[rankings['country_full'] == 'Congo'].index, 'country_full'] = 'Congo'
results.loc[results[results['home_team'] == 'Congo'].index, 'home_team'] = 'Congo'
results.loc[results[results['away_team'] == 'Congo'].index, 'away_team'] = 'Congo'

rankings.loc[rankings[rankings['country_full'] == 'Congo DR'].index, 'country_full'] = 'DR Congo'
results.loc[results[results['home_team'] == 'DR Congo'].index, 'home_team'] = 'DR Congo'
results.loc[results[results['away_team'] == 'DR Congo'].index, 'away_team'] = 'DR Congo'

rankings.loc[rankings[rankings['country_full'].str.contains('Swaziland')].index, 'country_full'] = 'Eswatini'
rankings.loc[rankings[rankings['country_full'].str.contains('Eswatini')].index, 'country_full'] = 'Eswatini'
results.loc[results[results['home_team'].str.contains('Eswatini')].index, 'home_team'] = 'Eswatini'
results.loc[results[results['away_team'].str.contains('Eswatini')].index, 'away_team'] = 'Eswatini'

rankings.loc[rankings[rankings['country_full'].str.contains('Korea DPR')].index, 'country_full'] = 'North Korea'
results.loc[results[results['home_team'].str.contains('North Korea')].index, 'home_team'] = 'North Korea'
results.loc[results[results['away_team'].str.contains('North Korea')].index, 'away_team'] = 'North Korea'

rankings.loc[rankings[rankings['country_full'].str.contains('USA')].index, 'country_full'] = 'United States'
results.loc[results[results['home_team'].str.contains('United States')].index, 'home_team'] = 'United States'
results.loc[results[results['away_team'].str.contains('United States')].index, 'away_team'] = 'United States'


rankings.loc[rankings[rankings['country_full'].str.contains('Ivoire')].index, 'country_full'] = 'Ivory Coast'
results.loc[results[results['home_team'].str.contains('Ivoire')].index, 'home_team'] = 'Ivory Coast'
results.loc[results[results['away_team'].str.contains('Ivoire')].index, 'away_team'] = 'Ivory Coast'

rankings.loc[rankings[rankings['country_full'].str.contains('Kitts and Nevis')].index, 'country_full'] = 'St. Kitts and Nevis'
results.loc[results[results['home_team'].str.contains('Kitts and Nevis')].index, 'home_team'] = 'St. Kitts and Nevis'
results.loc[results[results['away_team'].str.contains('Kitts and Nevis')].index, 'away_team'] = 'St. Kitts and Nevis'

rankings.loc[rankings[rankings['country_full'].str.contains('Korea Republic')].index, 'country_full'] = 'South Korea'
results.loc[results[results['home_team'].str.contains('Korea Republic')].index, 'home_team'] = 'South Korea'
results.loc[results[results['away_team'].str.contains('Korea Republic')].index, 'away_team'] = 'South Korea'

rankings.loc[rankings[rankings['country_full'].str.contains('St. Vin')].index, 'country_full'] = 'St. Vincent and the Grenadines'
results.loc[results[results['home_team'].str.contains('Vincent')].index, 'home_team'] = 'St. Vincent and the Grenadines'
results.loc[results[results['away_team'].str.contains('Vincent')].index, 'away_team'] = 'St. Vincent and the Grenadines'

rankings.loc[rankings[rankings['country_full'].str.contains('Iran')].index, 'country_full'] = 'Iran'
results.loc[results[results['home_team'].str.contains('Iran')].index, 'home_team'] = 'Iran'
results.loc[results[results['away_team'].str.contains('Iran')].index, 'away_team'] = 'Iran'

rankings.loc[rankings[rankings['country_full'].str.contains('Kyrgyz')].index, 'country_full'] = 'Kyrgyzstan'
results.loc[results[results['home_team'].str.contains('Kyrgyz')].index, 'home_team'] = 'Kyrgyzstan'
results.loc[results[results['away_team'].str.contains('Kyrgyz')].index, 'away_team'] = 'Kyrgyzstan'

results.loc[results[(results['home_team'] == 'Serbia') & (results['datetime'] < '2006-07-12 00:00:00')].index, 'home_team'] = 'Serbia and Montenegro'
results.loc[results[(results['away_team'] == 'Serbia') & (results['datetime'] < '2006-07-12 00:00:00')].index, 'away_team'] = 'Serbia and Montenegro'

rankings.loc[rankings[rankings['country_full'].str.contains('Lucia')].index, 'country_full'] = 'St. Lucia'
results.loc[results[results['home_team'].str.contains('Lucia')].index, 'home_team'] = 'St. Lucia'
results.loc[results[results['away_team'].str.contains('Lucia')].index, 'away_team'] = 'St. Lucia'

rankings.loc[rankings[rankings['country_full'].str.contains('Netherlands Antilles')].index, 'country_full'] = 'Curaçao'

rankings.loc[rankings[rankings['country_full'].str.contains('Verde')].index, 'country_full'] = 'Cape Verde'

rankings.loc[rankings[rankings['country_full'].str.contains('Brunei')].index, 'country_full'] = 'Brunei'

results.loc[results[results['home_team'].str.contains('United States Virgin Islands')].index, 'home_team'] = 'US Virgin Islands'
results.loc[results[results['away_team'].str.contains('United States Virgin Islands')].index, 'away_team'] = 'US Virgin Islands'

rankings.loc[rankings[rankings['country_full'].str.contains('Timor-Leste')].index, 'country_full'] = 'East Timor'

results.loc[results[results['home_team'].str.contains('Taiwan')].index, 'home_team'] = 'Chinese Taipei'
results.loc[results[results['away_team'].str.contains('Taiwan')].index, 'away_team'] = 'Chinese Taipei'

results.loc[results[results['home_team'].str.contains('Timor-Leste')].index, 'home_team'] = 'East Timor'
results.loc[results[results['away_team'].str.contains('Timor-Leste')].index, 'away_team'] = 'East Timor'

In [91]:
results_dict = results.to_dict('records')

In [92]:
# Creating 10 game scoring averages for teams
# Need to run twice

for i in results_dict:
    hometeam = i['home_team']
    matchday = i['datetime']
    h_goals_for = []
    h_goals_against = []
    for j in results_dict:
        if (j['home_team'] == hometeam) and (j['datetime'] < matchday):
            h_goals_for.append(j['home_score'])
            h_goals_against.append(j['away_score'])
            # print(hometeam), print(h_goals_for), print(h_goals_against)
            if h_goals_for == []:
                i['h_goals_for_avg'] = 0
            elif len(h_goals_for) < 10:
                i['h_goals_for_avg'] = np.mean(h_goals_for)
            else:
                i['h_goals_for_avg'] = np.mean(h_goals_for[-10:])
            if h_goals_against == []:
                i['h_goals_against_avg'] = 0
            elif len(h_goals_against) < 10:
                i['h_goals_against_avg'] = np.mean(h_goals_against)
            else:
                i['h_goals_against_avg'] = np.mean(h_goals_against[-10:])

for i in results_dict:
    awayteam = i['away_team']
    matchday = i['datetime']
    a_goals_for = []
    a_goals_against = []
    for j in results_dict:
        if (j['away_team'] == awayteam) and (j['datetime'] < matchday):
            a_goals_for.append(j['away_score'])
            a_goals_against.append(j['home_score'])
            # print(hometeam), print(h_goals_for), print(h_goals_against)
            if a_goals_for == []:
                i['a_goals_for_avg'] = 0
            elif len(a_goals_for) < 10:
                i['a_goals_for_avg'] = np.mean(a_goals_for)
            else:
                i['a_goals_for_avg'] = np.mean(a_goals_for[-10:])
            if a_goals_against == []:
                i['a_goals_against_avg'] = 0
            elif len(a_goals_against) < 10:
                i['a_goals_against_avg'] = np.mean(a_goals_against)
            else:
                i['a_goals_against_avg'] = np.mean(a_goals_against[-10:])

results = pd.DataFrame(results_dict)
results.tail()

,date,home_team,away_team,home_score,away_score,neutral,home_rank,away_rank,h_goals_for_avg,h_goals_against_avg,a_goals_for_avg,a_goals_against_avg,datetime,match_type_FIFA_WCQ,match_type_Friendly,match_type_Qualifier,match_type_Tournament/Cup_Match
23207,2021-09-01,Latvia,Gibraltar,3,1,0,136,194,0.6,1.8,0.2,2.6,2021-09-01,1,0,0,0
23208,2021-09-01,Turkey,Montenegro,2,2,0,39,67,1.9,1.6,0.7,1.6,2021-09-01,1,0,0,0
23209,2021-09-01,Malta,Cyprus,3,0,0,177,99,1.2,1.9,0.8,2.1,2021-09-01,1,0,0,0
23210,2021-09-01,Slovenia,Slovakia,1,1,0,66,38,1.8,0.4,0.6,1.5,2021-09-01,1,0,0,0
23211,2021-09-01,Russia,Croatia,0,0,0,41,18,1.4,1.1,1.3,1.9,2021-09-01,1,0,0,0

In [93]:
results_dict = results.to_dict('records')

In [94]:
rankings_dict = rankings.to_dict('records')

In [95]:
# Function that brings home rankings into results
# Need to run twice

def home_rank(row):
    try:
        hometeam = row['home_team']
        matchday = row['datetime']

        hometeam_rankings = []
        for i in rankings_dict:
            if i['country_full'] == hometeam:
                hometeam_rankings.append(i)

        previous_rankings = []
        for i in hometeam_rankings:
            if i['datetime'] <= matchday:
                previous_rankings.append(i)
        # print(hometeam), print(matchday)

        return previous_rankings[-1]['rank']

    except:
        print(hometeam), print(matchday)
        return -1

In [96]:
# Applying function to dataframe
# Need to run twice

results['home_rank'] = results.apply(home_rank, axis=1)

In [97]:
results[results['home_rank'] == -1].shape
# Serbia & Montenegro and St. Kitts and Nevis errors fixed after running drops twice???

(0, 17)

In [98]:
#  rankings[rankings['country_full'] == 'DR Congo']
#  checks for errors when assigning ranks

In [99]:
#  results[(results['home_team'] == 'DR Congo') & (results['datetime'] < '1999-12-22 00:00:00')]
#  checks for errors when assigning ranks

In [100]:
#  results[results['home_team'] == 'DR Congo']
#  checks for errors when assigning ranks

In [101]:
# Function that brings away rankings into results
# Need to run twice

def away_rank(row):
    try:
        awayteam = row['away_team']
        matchday = row['datetime']

        awayteam_rankings = []
        for i in rankings_dict:
            if i['country_full'] == awayteam:
                awayteam_rankings.append(i)

        previous_rankings = []
        for i in awayteam_rankings:
            if i['datetime'] <= matchday:
                previous_rankings.append(i)
        # print(awayteam), print(matchday)

        return previous_rankings[-1]['rank']

    except:
        print(awayteam), print(matchday)
        return -1

In [102]:
# Applying function to dataframe
# Need to run

results['away_rank'] = results.apply(away_rank, axis=1)

In [103]:
results[results['away_rank'] == -1].shape
# Serbia & Montenegro and St. Kitts and Nevis errors fixed after running drops twice???

(0, 17)

In [57]:
#  rankings[rankings['country_full'].str.contains('USA')]
#  checks for errors when assigning ranks

In [58]:
#  results[(results['away_team'] == 'United States') & (results['datetime'] < '2021-08-21 00:00:00')]
#  checks for errors when assigning ranks

In [59]:
#  results[results['away_team'].str.contains('United States')]
#  checks for errors when assigning ranks

In [60]:
results['neutral'] = results['neutral'].map({True: 1, False: 0})

In [61]:
results.dropna(inplace=True)

In [62]:
results['home_score'] = results['home_score'].astype(int)
results['away_score'] = results['away_score'].astype(int)
results['home_rank'] = results['home_rank'].astype(int)
results['away_rank'] = results['away_rank'].astype(int)

In [63]:
# dropping games with more than 10 goals scored by one team (decided after EDA after seeing heavy outliers)

results.drop(results[results['home_score'] > 10].index, inplace=True)
results.drop(results[results['away_score'] > 10].index, inplace=True)

In [64]:
# Dropping these columns because neutral column covers this information

results.drop(columns=['city', 'country'], inplace=True)

In [65]:
results = results.rename(columns={'tournament': 'match_type'})

In [66]:
# Condensing like match types into groups

results.loc[results[results['match_type'] == 'FIFA World Cup qualification'].index, 'match_type'] = 'FIFA_WCQ'
results.loc[results[results['match_type'].str.contains('FIFA World Cup')].index, 'match_type'] = 'FIFA_WC'
results.loc[results[results['match_type'].str.contains('qualification')].index, 'match_type'] = 'Qualifier'
results.loc[results[results['match_type'].str.contains('Cup')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Copa')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Tournament')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Championship')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('League')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Games')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('UEFA Euro')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Festival')].index, 'match_type'] = 'Tournament/Cup_Match'
results.loc[results[results['match_type'].str.contains('Tournoi')].index, 'match_type'] = 'Tournament/Cup_Match'

In [67]:
results['match_type'].value_counts()

Friendly                8530
FIFA_WCQ                5236
Tournament/Cup_Match    5073
Qualifier               4065
FIFA_WC                  436
Name: match_type, dtype: int64

In [68]:
results = pd.get_dummies(results, columns=['match_type'], drop_first=True)

In [69]:
# Check indexing issues to fix (not many columns so will drop them for now)

results.drop(results[results['home_rank'] == results['away_rank']].index, inplace=True)

In [105]:
results.to_csv('./data/cleaned_results_and_rankings.csv', index=False)

---

### Ensuring our qualifying fixtures have the same features as our results data set.

In [71]:
qualifying_fixtures.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,2021-09-02,Canada,Honduras,1.0,1.0,FIFA World Cup qualification,Toronto,Canada,False
1,2021-09-02,Panama,Costa Rica,0.0,0.0,FIFA World Cup qualification,Panama City,Panama,False
2,2021-09-02,Mexico,Jamaica,2.0,1.0,FIFA World Cup qualification,Mexico City,Mexico,False
3,2021-09-02,El Salvador,United States,0.0,0.0,FIFA World Cup qualification,San Salvador,El Salvador,False
4,2021-09-05,Jamaica,Panama,0.0,3.0,FIFA World Cup qualification,Kingston,Jamaica,False

In [72]:
qualifying_fixtures['home_rank'] = 0
qualifying_fixtures['away_rank'] = 0
qualifying_fixtures['h_goals_for_avg'] = 0
qualifying_fixtures['h_goals_against_avg'] = 0
qualifying_fixtures['a_goals_for_avg'] = 0
qualifying_fixtures['a_goals_against_avg'] = 0

In [73]:
qualifying_fixtures_dict = qualifying_fixtures.to_dict('records')

In [74]:
# Pulling in the most recent 10 game goal average prior to WCQ matches

for i in qualifying_fixtures_dict:
    hometeam = i['home_team']
    h_goals_for_avgs = []
    h_goals_against_avgs = []
    for j in results_dict:
        if j['home_team'] == hometeam:
            h_goals_for_avgs.append(j['h_goals_for_avg'])
            h_goals_against_avgs.append(j['h_goals_against_avg'])
            i['h_goals_for_avg'] = h_goals_for_avgs[-1]
            i['h_goals_against_avg'] = h_goals_against_avgs[-1]
            
for i in qualifying_fixtures_dict:
    awayteam = i['away_team']
    a_goals_for_avgs = []
    a_goals_against_avgs = []
    for j in results_dict:
        if j['away_team'] == awayteam:
            a_goals_for_avgs.append(j['a_goals_for_avg'])
            a_goals_against_avgs.append(j['a_goals_against_avg'])
            i['a_goals_for_avg'] = a_goals_for_avgs[-1]
            i['a_goals_against_avg'] = a_goals_against_avgs[-1]

In [75]:
qualifying_fixtures = pd.DataFrame(qualifying_fixtures_dict)

In [76]:
qualifying_fixtures['datetime'] = pd.to_datetime(qualifying_fixtures['date'])

In [77]:
# Ensuring country name matches in rankings and qualifying_fixtures dataframes

rankings.loc[rankings[rankings['country_full'].str.contains('USA')].index, 'country_full'] = 'United States'
qualifying_fixtures.loc[qualifying_fixtures[qualifying_fixtures['home_team'].str.contains('USA')].index, 'home_team'] = 'United States'
qualifying_fixtures.loc[qualifying_fixtures[qualifying_fixtures['away_team'].str.contains('USA')].index, 'away_team'] = 'United States'

In [78]:
# Assigning rankings to home teams in qualifiers

qualifying_fixtures['home_rank'] = qualifying_fixtures.apply(home_rank, axis=1)

In [79]:
# Assigning rankings to away teams in qualifiers

qualifying_fixtures['away_rank'] = qualifying_fixtures.apply(away_rank, axis=1)

In [80]:
# None of the qualifiers are played in neutral locations

qualifying_fixtures['neutral'] = 0

In [81]:
qualifying_fixtures['home_rank'] = qualifying_fixtures['home_rank'].astype(int)
qualifying_fixtures['away_rank'] = qualifying_fixtures['away_rank'].astype(int)

In [82]:
# Dropping columns that are not needed for models to predict

qualifying_fixtures.drop(columns=['city', 'country', 'tournament'], inplace=True)

In [83]:
# Ensuring results and qualifying_fixtures have the same columns

results.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score', 'neutral',
       'home_rank', 'away_rank', 'h_goals_for_avg', 'h_goals_against_avg',
       'a_goals_for_avg', 'a_goals_against_avg', 'datetime',
       'match_type_FIFA_WCQ', 'match_type_Friendly', 'match_type_Qualifier',
       'match_type_Tournament/Cup_Match'],
      dtype='object')

In [84]:
# Ensuring results and qualifying_fixtures have the same columns

qualifying_fixtures.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score', 'neutral',
       'home_rank', 'away_rank', 'h_goals_for_avg', 'h_goals_against_avg',
       'a_goals_for_avg', 'a_goals_against_avg', 'datetime'],
      dtype='object')

In [85]:
qualifying_fixtures['match_type_FIFA_WCQ'] = 1
qualifying_fixtures['match_type_Friendly'] = 0
qualifying_fixtures['match_type_Qualifier'] = 0
qualifying_fixtures['match_type_Tournament/Cup_Match'] = 0

In [86]:
qualifying_fixtures.head()

,date,home_team,away_team,home_score,away_score,neutral,home_rank,away_rank,h_goals_for_avg,h_goals_against_avg,a_goals_for_avg,a_goals_against_avg,datetime,match_type_FIFA_WCQ,match_type_Friendly,match_type_Qualifier,match_type_Tournament/Cup_Match
0,2021-09-02,Canada,Honduras,1.0,1.0,0,59,63,3.2,0.2,1.1,1.9,2021-09-02,1,0,0,0
1,2021-09-02,Panama,Costa Rica,0.0,0.0,0,74,44,2.4,1.1,0.9,1.3,2021-09-02,1,0,0,0
2,2021-09-02,Mexico,Jamaica,2.0,1.0,0,9,50,1.8,0.5,1.7,1.3,2021-09-02,1,0,0,0
3,2021-09-02,El Salvador,United States,0.0,0.0,0,64,10,1.5,0.1,1.0,0.9,2021-09-02,1,0,0,0
4,2021-09-05,Jamaica,Panama,0.0,3.0,0,50,74,2.3,0.8,1.1,1.6,2021-09-05,1,0,0,0

In [87]:
qualifying_fixtures.to_csv('./data/cleaned_qualifying_fixtures.csv', index=False)

---