In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import dataframe_image as dfi

In [137]:
current_CONCACAF_table = pd.read_csv('./data/current_table_12.14.2021.csv')
current_CONCACAF_table

,rank,team_name,matches_played,wins,draws,losses,goals_for,goals_against,goal_differential,points
0,1,Canada,8,4,4,0,13,5,8,16
1,2,USA,8,4,3,1,12,5,7,15
2,3,Mexico,8,4,2,2,11,7,4,14
3,4,Panama,8,4,2,2,11,9,2,14
4,5,Costa Rica,8,2,3,3,6,7,-1,9
5,6,Jamaica,8,1,4,3,6,10,-4,7
6,7,El Salvador,8,1,3,4,4,10,-6,6
7,8,Honduras,8,0,3,5,5,15,-10,3

In [138]:
dfi.export(current_CONCACAF_table, './images/current_table.png')

In [139]:
predictions_dict = {'team_name': ['Canada', 'United States', 'Mexico', 'Panama', 'Costa Rica', 'Jamaica', 'El Salvador', 'Honduras'], 
'matches_played': [0, 0, 0, 0, 0, 0, 0, 0], 'wins': [0, 0, 0, 0, 0, 0, 0, 0], 'draws': [0, 0, 0, 0, 0, 0, 0, 0],
'losses': [0, 0, 0, 0, 0, 0, 0, 0], 'goals_for': [0, 0, 0, 0, 0, 0, 0, 0], 'goals_against': [0, 0, 0, 0, 0, 0, 0, 0], 
'goal_differential': [0, 0, 0, 0, 0, 0, 0, 0], 'points': [0, 0, 0, 0, 0, 0, 0, 0]}

predicted_table = pd.DataFrame(predictions_dict)
predicted_table

,team_name,matches_played,wins,draws,losses,goals_for,goals_against,goal_differential,points
0,Canada,0,0,0,0,0,0,0,0
1,United States,0,0,0,0,0,0,0,0
2,Mexico,0,0,0,0,0,0,0,0
3,Panama,0,0,0,0,0,0,0,0
4,Costa Rica,0,0,0,0,0,0,0,0
5,Jamaica,0,0,0,0,0,0,0,0
6,El Salvador,0,0,0,0,0,0,0,0
7,Honduras,0,0,0,0,0,0,0,0

In [140]:
qualifying_fixtures = pd.read_csv('./data/qualifier_predictions.csv')
# qualifying_fixtures

In [141]:
qualifying_fixtures_dict = qualifying_fixtures.to_dict('records')
# qualifying_fixtures_dict[0]

predicted_table_dict = predicted_table.to_dict('records')
# predicted_table_dict[0]

In [142]:
for i in qualifying_fixtures_dict:
    for j in predicted_table_dict:
        if i['home_team'] == j['team_name']:
            j['matches_played'] = j['matches_played'] + 1
            j['goals_for'] = j['goals_for'] + i['home_score']
            j['goals_against'] = j['goals_against'] + i['away_score']
            j['goal_differential'] = j['goal_differential'] + i['home_score'] - i['away_score']
            if i['home_score'] > i['away_score']:
                j['wins'] = j['wins'] + 1
                j['points'] = j['points'] + 3
            elif i['home_score'] == i['away_score']:
                j['draws'] = j['draws'] + 1
                j['points'] = j['points'] + 1
            elif i['home_score'] < i['away_score']:
                j['losses'] = j['losses'] + 1
    
# pd.DataFrame(predicted_table_dict)

for i in qualifying_fixtures_dict:
    for j in predicted_table_dict:
        if i['away_team'] == j['team_name']:
            j['matches_played'] = j['matches_played'] + 1
            j['goals_for'] = j['goals_for'] + i['away_score']
            j['goals_against'] = j['goals_against'] + i['home_score']
            j['goal_differential'] = j['goal_differential'] + i['away_score'] - i['home_score']
            if i['away_score'] > i['home_score']:
                j['wins'] = j['wins'] + 1
                j['points'] = j['points'] + 3
            elif i['away_score'] == i['home_score']:
                j['draws'] = j['draws'] + 1
                j['points'] = j['points'] + 1
            elif i['away_score'] < i['home_score']:
                j['losses'] = j['losses'] + 1
    
predicted_table = pd.DataFrame(predicted_table_dict)
predicted_table

,team_name,matches_played,wins,draws,losses,goals_for,goals_against,goal_differential,points
0,Canada,14,3,7,4,13,15,-2,16
1,United States,14,10,4,0,28,6,22,34
2,Mexico,14,12,2,0,33,4,29,38
3,Panama,14,0,4,10,8,27,-19,4
4,Costa Rica,14,2,9,3,14,17,-3,15
5,Jamaica,14,4,7,3,15,16,-1,19
6,El Salvador,14,2,5,7,8,19,-11,11
7,Honduras,14,2,4,8,8,23,-15,10

In [143]:
predicted_table = predicted_table.reindex(predicted_table.sort_values(['points', 'goal_differential', 'goals_for'], ascending=[False, False, False]).index)
predicted_table.reset_index(inplace=True)

predicted_table.rename(columns={'index': 'rank'}, inplace=True)
predicted_table['rank'] = list(range(1,9))
predicted_table.set_index(predicted_table['rank'], inplace=True)
predicted_table.drop(columns=['rank'], inplace=True)
predicted_table

,team_name,matches_played,wins,draws,losses,goals_for,goals_against,goal_differential,points
rank,,,,,,,,,
1,Mexico,14,12,2,0,33,4,29,38
2,United States,14,10,4,0,28,6,22,34
3,Jamaica,14,4,7,3,15,16,-1,19
4,Canada,14,3,7,4,13,15,-2,16
5,Costa Rica,14,2,9,3,14,17,-3,15
6,El Salvador,14,2,5,7,8,19,-11,11
7,Honduras,14,2,4,8,8,23,-15,10
8,Panama,14,0,4,10,8,27,-19,4

In [144]:
dfi.export(predicted_table, './images/predicted_table.png')

In [145]:
# check errors in predictions
# check against baseline scores for home/away goals
# maybe try random forest regressor if time allows
# move from GA github to personal github